<!DOCTYPE html>
<html lang="en">

<div class="paragraph-9"><p style="line-height:1.295; text-align:justify; border-bottom:solid #dfdfdf 0.75pt; margin-top:20px; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: small-caps; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">TÉRMINOS Y CONDICIONES DE ARTESANOS ONLINE</span></span></span></span></span></span></span><br>
&nbsp;</p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><br>
<span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Los presentes Términos y Condiciones de la tienda en línea www.ArtesanosOnline.com (el “</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:underline"><span style="text-decoration-skip-ink:none">Sitio</span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">”) establecen las condiciones generales de contratación que son aplicables a las operaciones de compraventa que se llevan a cabo entre FUNDACION DE HACIENDAS DEL MUNDO MAYA, A.C. (“</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:underline"><span style="text-decoration-skip-ink:none">Artesano Online</span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">”) y los usuarios del Sitio (los “</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:underline"><span style="text-decoration-skip-ink:none">Clientes</span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">”).</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">I.- Requisitos para uso del Sitio.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Para poder realizar una compra en este Sitio el Cliente deberá registrarse y crear una cuenta del Sitio, mediante la cual proporcionará un usuario y contraseña para acceder al Sitio</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">. Consulte nuestro Aviso de privacidad para conocer el tratamiento y protección de sus datos personales en la página [*]. Al crear una cuenta en el Sitio, nuestra plataforma vinculará su número de cuenta con su dirección de correo electrónico y con la contraseña de seguridad que el Cliente elegirá y que sólo el Cliente debe conocer.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">El Cliente solamente podrá realizar transacciones si ha ingresado al Sitio mediante el uso de su contraseña secreta. En términos de las disposiciones contenidas en el Código de Comercio, el uso de esta contraseña nos permite identificarlo en el ambiente digital y atribuirle los actos y transacciones que realiza en la Tienda en Línea.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano online tiene derecho: (i) a asumir que los mensajes de datos asociados a su firma electrónica o cuenta proveniente del Cliente vinculado a dicha firma y/o cuenta y a actuar en consecuencia del mensaje recibido para atender su solicitud y; (ii) a considerar que el mensaje de datos que nos hizo llegar corresponde expresamente al que el Cliente nos quiso hacer llegar</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Para registrarse y comprar en este Sitio el Cliente debe tener al menos 18 años de edad. Artesano Online no fomenta ni permite de manera consciente que menores de edad puedan hacer uso de este Sitio web. Si usted no ha cumplido 18 años o su capacidad contractual está limitada por la legislación aplicable, no debe hacernos llegar Órdenes de Compra o utilizar de manera alguna nuestro Sitio web.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Este Sitio sólo puede ser utilizado para adquirir artículos que vayan a ser entregados en algún domicilio localizado en México.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">II.- Uso del Sitio</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Si el Cliente cumple con los requisitos mencionados anteriormente, Artesano Online le otorgará una licencia personal, no exclusiva, revocable e intransferible para que pueda usar nuestro Sitio para uso exclusivamente personal, privado y sin fines de lucro.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Esta licencia se encuentra sujeta a restricciones y no incluye, entre otros, los siguientes usos: (i) utilizar el Sitio para revender productos o hacer cualquier otro uso comercial del Sitio web o de los Contenidos del Sitio; (ii) llevar a cabo la modificación, adaptación, traducción, reversión de ingeniería, desensamblaje, descompilación o conversión de cualquier formato o programa de cómputo que exista del Sitio. El Cliente solo está autorizado para utilizar el código HTML o cualquier otro código de este Sitio web en la forma en que Usted lo recibe a través de su navegador; tampoco queda autorizado para poner dichos códigos a disposición de un tercero; (iii) copiar, imitar, replicar para su uso en servidores espejo, reproducir, distribuir, publicar, descargar, mostrar o transmitir cualquier Contenido del Sitio (incluyendo marcas registradas) en cualquier forma o por cualquier medio; esta restricción incluye, pero no se limita a los siguientes medios: medios electrónicos, mecánicos, medios de fotocopiado, grabación o cualquier otro medio; (iv) recopilar y usar cualquier listado de productos o descripciones de productos; (v) hacer modificaciones al Sitio Web y/o a los Contenidos del Sitio o realizar cualquier obra derivada a partir de dichos materiales o; (vi) utilizar cualquier mecanismo o herramienta automatizada o cualquier método o tecnología similar que tenga como finalidad o como consecuencia, el realizar la extracción, obtención o recopilación, directa o indirecta, de los Contenidos del Sitio, o de cualquier información o datos personales relacionados con el Sitio web.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Excepto por los usos del Sitio web que han sido autorizados en esta cláusula, se hace notar que Artesano Online no le otorga al Cliente de manera explícita o implícita, derecho o licencia alguna para que pueda utilizar cualquier patente, marca registrada, derecho de autor, derechos de acceso, uso o explotación de bases de datos o cualquier otro derecho de propiedad intelectual que pertenezca a Artesano Online, sus afiliadas o a cualquier tercero, en los términos de la legislación aplicable (incluyendo derechos de autor o de propiedad industrial).</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online se reserva el derecho de cancelar la cuenta del Cliente en nuestro Sitio y prohibirle el acceso o uso del mismo en cualquier momento si incumple con cualquiera de estos términos y condiciones o si permite o tolera que un tercero incumpla con dichos términos. Se hace notar que la realización de conductas que contravengan los presentes Términos y Condiciones del Sitio puede resultar también en una violación a la ley (incluyendo la legislación en materia de derechos de autor, propiedad industrial, leyes mercantiles, de telecomunicaciones o legislación penal, entre otras disposiciones).</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">III.- Obligaciones de los usuarios del Sitio.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Al utilizar este sitio, Usted está obligado a lo siguiente:</span></span></span></span></span></span></span></p>

<ol>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">a. Cumplir con estos Términos y Condiciones.</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">b. Proveer al Sitio información completa, correcta y actualizada. El Cliente se obliga a notificar a Artesano Online cualquier cambio en la información previamente proporcionada (incluyendo direcciones de entrega). Para tal efecto, por favor utilice las opciones que Artesano Online ofrece para corregir sus datos personales en términos de nuestro Aviso de privacidad</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">c. Mantener de manera secreta y confidencial su contraseña de acceso al Sitio web y cualquier otro dato de creación de su firma electrónica. En caso de que el Cliente considere que ha perdido el control sobre la confidencialidad de su cuenta o de su contraseña o dicha confidencialidad se encuentra en riesgo, notifique esta situación inmediatamente a Artesano Online. Usted es responsable de cualquier transacción que sea realizada a través de su cuenta (hecha por el Cliente mismo o por un tercero) ocurrida hasta antes de que el Cliente nos haya notificado esta situación. Artesano Online no asume obligación alguna con respecto a estas transacciones.</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">d. El Usuario se obliga a no utilizar el Sitio para: (i) participar en, fomentar o hacer apología de un delito; para realizar acciones que violen los derechos de terceros o que resulten en la violación de alguna ley nacional o internacional; (ii) hacerse pasar por otra persona u entidad o usar de manera falsa o fraudulenta cualquier derecho asociado a su membresía, y (iii) difundir a través de la plataforma del Sitio web cualquier información, programa o código que pudiera causar un daño incluyendo un virus, troyanos, gusanos u otros códigos de programación informática que pudieran dañar, espiar, interferir, interceptar o extraer información o datos personales de nuestros sistemas informáticos, de la plataforma sobre la que opera la tienda en línea, o de los equipos, redes, sistemas y programas de cómputo que utilicen nuestros Clientes para interactuar con el Sitio web.</span></span></span></span></span></span></span></li>
</ol>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online opera este Sitio; sin embargo, no tiene capacidad para monitorear que las diversas personas y entidades que participan en el Sitio web cumplan con las leyes aplicables; por lo tanto,Artesano Online no asume responsabilidad alguna por cualquier contenido publicado o cargado al Sitio web por terceros incluyendo contenidos que pudieran dar lugar a error, difamación, calumnia, omisión, amenazas, falsedad o que pudieran ser considerados como de carácter pornográfico o que hagan apología o fomenten algún acto ilícito.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online tiene el derecho de (pero no se encuentra obligado a) investigar cualquier conducta de un Cliente que sea reportada o percibida como ilegal o que pudiera contravenir algunos de los Términos y Condiciones. Si el Cliente identifica una conducta que considere violatoria de algún derecho en nuestro Sitio web (incluyendo alguna violación de marcas, derechos de autor o de alguna otra ley), por favor envíenos un correo a </span></span></span></span></span></span><a href="mailto:ArtesanosOnli@gmail.com" style="text-decoration:none"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#0563c1"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:underline"><span style="text-decoration-skip-ink:none">ArtesanosOnli@gmail.com</span></span></span></span></span></span></span></a><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"> o llámenos al siguiente teléfono </span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#2f2f30"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">55 5257 0097 ext. 100.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">El Cliente se obliga a indemnizar a Artesano Online y sus empleados y representantes con respecto a cualquier daño o perjuicio que Artesano Online sea obligado a pagar como consecuencia de algún reclamo, acción o demanda que sea entablada en el contrato de Artesano Online por algún tercero, cuando dicha demanda o acción se funde en, o se relacione con, el uso que el Cliente ha hecho del Sitio web o su incumplimiento de cualquiera de los Términos y Condiciones del Sitio web o de los derechos de terceros.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">IV.- Precios.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Los precios de los artículos están expresados en Soles, la Moneda de curso legal en Peru . Los precios de los artículos son los que se muestran en el Sitio y, salvo que se indique lo contrario, incluyen los impuestos aplicables. Los precios NO incluyen gastos de envío, los cuales deberá pagar el Cliente por separado. Antes de hacer clic en el botón de pago, el Cliente podrá ver el precio total a ser pagado y los descuentos que pudieran ser aplicables, así como el tiempo de entrega determinado por el código postal ingresado en la plataforma; los impuestos a ser pagados aparecerán desglosados en los términos que establezca la regulación aplicable.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">V.- Disponibilidad de artículos.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online realiza esfuerzos para asegurar que la descripción de las mercancías o servicios que se incluyen en nuestro Catálogo sea precisa, asimismo, para asegurar que los productos se encuentren disponibles al precio especificado. Sin embargo, el Cliente acepta que en la medida permitida por las leyes,Artesano Online:</span></span></span></span></span></span></span></p>

<ol>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Informa que pueden existir variaciones del Catálogo o productos, esto debido a materiales naturales y artificiales. También existen variaciones visuales debido al entorno en el que el producto se encuentre, como tipo de iluminación, natural, cálida, fría, variable, etc. Así mismo, es causa de matices o tonalidades el color de muros o el entorno en el que se exhiben o se monten los productos del catálogo. Las descripciones pueden variar de acuerdo a cada fabricante y el uso de cada material en la elaboración de los artículos.</span></span></span></span></span></span></span></li>
</ol>
&nbsp;

<ol start="2">
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Se reserva el derecho de cambiar o sustituir, en cualquier momento, cualquier artículo del Catálogo, los precios o especificaciones publicados en el Sitio y cualquier otro Contenido del Sitio; por lo general, realizaremos estas modificaciones de tiempo en tiempo, sin previo aviso; no asumimos responsabilidad por los daños o perjuicios que pudieran causarle el cambio, sustitución o la discontinuidad de un artículo;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Tiene el derecho de revocar cualquier oferta o promoción aplicable a las mercancías, incluso antes de que concluya la vigencia de la promoción; en todo caso, Artesano Online notificará la revocación de la oferta o promoción a través del Sitio web. Artesano Online respetará los derechos de los consumidores cuyas órdenes hayan sido aceptadas durante la vigencia de la oferta o promoción en los términos de la regulación aplicable;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">No garantiza que los bienes o servicios que se encuentran incluidos en nuestro Catálogo estarán disponibles cuando el Cliente nos envíe su Orden de Compra o posteriormente;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Se reserva el derecho de limitar las cantidades de mercancías puestas a disposición para la venta a través del Sitio, en la medida que la ley lo permita.</span></span></span></span></span></span></span></li>
</ol>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">VI.- Orden de Compra</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Antes de realizar su Orden de Compra, Usted podrá revisar las características y especificaciones técnicas de la mercancía y los términos y condiciones que son aplicables a la adquisición del artículo, incluyendo el precio, cargos, métodos de pago, y condiciones especiales que podrían ser aplicables a la entrega de la mercancía. Esta información aparece generalmente en las fichas de información asociadas a cada producto. En caso de que el Cliente tenga alguna duda respecto de la mercancía o el servicio que pretende adquirir, por favor póngase en contacto con Artesano Online </span></span></span></span></span></span><a href="mailto:ArtesanosOnli@gmail.com" style="text-decoration:none"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#0563c1"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:underline"><span style="text-decoration-skip-ink:none">ArtesanosOnli@gmail.com</span></span></span></span></span></span></span></a><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"> antes de su compra.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Por favor considere el hecho de que los artículos se encuentren en el Catálogo en el Sitio no constituye una oferta unilateral de venta de estas mercancías por parte de Artesano Online.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Cuando el Cliente nos hace llegar una Orden de Compra, el Cliente realiza una oferta para adquirir de nosotros una determinada cantidad de mercancías. En caso de que nosotros aceptemos su oferta, el Cliente recibirá un mensaje de datos de Confirmación de Compra. Por lo general, si no contamos con existencia suficiente de mercancías o requerimos información adicional de su parte para procesar la transacción, hacemos de su conocimiento estas situaciones antes de enviarle una Confirmación de Compra.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">VII.- Propiedad de las mercancías.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">La compraventa se perfecciona y es obligatoria para ambas partes en el momento en que el Cliente recibe de Artesano Online un mensaje de Confirmación de Compra a través del Sitio web; por lo general, nosotros realizamos el cargo en su tarjeta de crédito al momento en que emitimos su Confirmación de Compra. La propiedad de las mercancías le es transmitida en el momento en que el Cliente recibe la Confirmación de Compra o en el momento en que Artesano Online recibe su pago, independientemente de si el pago fue pactado en parcialidades o de manera total.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">VIII.- Riesgos de pérdida o deterioro del artículo.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">El Cliente es responsable de la pérdida, daño o deterioro de su mercancía a partir del momento en que se realiza la entrega de la misma en el domicilio establecido en la Orden de Compra. Una vez entregados los productos y sin que se haya reportado algún daño al operador, es responsabilidad de Cliente y no se genera garantía, por tal, es obligación del el Cliente, cerciorarse que sus productos se entreguen en óptimo estado.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">IX.- Cancelación de Órdenes de Compra por parte de Artesano Online.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">El Cliente acepta que Artesano Online gozará del derecho de rescindir o cancelar total o parcialmente cualquier transacción con posterioridad a la Confirmación de Compra y hasta antes de la entrega. En este caso, Artesano Online se pondrá en contacto con el Cliente y le hará saber que su orden fue cancelada. En los casos en que se determine la cancelación de una Orden de Compra, no se hará el cargo a la tarjeta de crédito del Cliente o bien, le informaremos que su Orden de Compra ha sido cancelada y reembolsaremos su dinero a la tarjeta de crédito que se utilizó como medio de pago.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">El Cliente acepta que Artesano Online rescinda o cancele la compra y realice la devolución del dinero correspondiente cuando la cancelación se derive de, o se haya originado por, entre otras, las siguientes situaciones:</span></span></span></span></span></span></span></p>

<ol>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Fallas en los sistemas informáticos de Artesano Online o de sus proveedores;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">La existencia de imprecisiones o errores en la información ofrecida para alguna mercancía en nuestro Catálogo, o respecto de su precio o disponibilidad;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">&nbsp;Errores tipográficos o de captura;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">&nbsp;Acciones tomadas por Artesano Online para garantizar la equidad entre Clientes en caso de que varios Clientes soliciten los mismos artículos y la existencia de los mismos sea limitada;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Posibles riesgos relacionados con el Cliente o su método de pago que sean identificados por nuestros departamentos de crédito o prevención de fraudes;</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">situaciones fuera del control de Artesano Online que limiten o impidan la entrega de alguna mercancía.</span></span></span></span></span></span></span></li>
	<li style="list-style-type:lower-alpha"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En caso de que Artesano Online determine que el Cliente ha incumplido con alguno de los términos establecidos en los Documentos Contractuales del Sitio.</span></span></span></span></span></span></span></li>
</ol>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">X.- Pagos</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Pagos en línea.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Nuestro sistema de pago en línea acepta únicamente pagos a través de tarjetas de crédito </span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">y débito </span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Visa, MasterCard y American Express y pagos a través de Stripe y PayPal. Antes de poder completar su Orden de Compra, el Cliente deberá haber proporcionado a través del Sitio el domicilio asociado a su tarjeta y los datos asociados a su tarjeta de crédito o débito, incluyendo su número de tarjeta, el nombre del titular, la fecha de vencimiento y el código de seguridad de la tarjeta o bien los datos solicitados en PayPay y Stripe. Los términos específicos de pago le serán informados en las fichas de información del artículo.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online no almacena la información de su tarjeta de crédito; estos datos son obtenidos directamente del Cliente, a través de una sección protegida por altos niveles de seguridad en nuestro Sitio web. El procesador de pagos solicita la autorización de su compra al banco emisor. Artesano Online ha adoptado diversas medidas para asegurar que su pago en línea se realice de manera segura y confiable.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">XI.- Comisión bancaria</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">El Cliente deberá pagar la comisión bancaria que, en su caso, se llegase a cobrar por el banco emisor de la tarjeta utilizada para la compra de productos.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">XII.- Facturación</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En caso de requerir factura, deberá solicitarla al momento de efectuar su compra y como máximo hasta el último día hábil del mes en que ésta se haya realizado. Para ello deberá proporcionar los datos fiscales requeridos al correo electrónico </span></span></span></span></span></span><a href="mailto:ArtesanosOnli@gmail.com" style="text-decoration:none"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#0563c1"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:underline"><span style="text-decoration-skip-ink:none">ArtesanosOnli@gmail.com</span></span></span></span></span></span></span></a><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"> Su factura le será enviada en un periodo de 24 horas hábiles después de que el Cliente la solicite.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">XIII.- Envío de las mercancías.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online enviará las mercancías adquiridas por los Clientes mediante servicio de mensajería intermediaria. Los términos aplicables a la entrega de las mercancías varían dependiendo del tipo de artículo adquirido, materiales y de su tamaño. La entrega de los artículos se hará a pie de calle, en caso de que el Cliente requiera maniobras ajenas, este asumirá las responsabilidades de daños y costos extra, estas actividades tendrán que ser contratadas por su cuenta. El Cliente podrá revisar los costos y plazos aproximados para la entrega de los productos seleccionados.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Una vez que Artesano Online efectúe la entrega de la mercancía al servicio de mensajería, la entrega de la misma al domicilio del Cliente a pie de calle, es exclusiva responsabilidad del servicio de mensajería, por lo que el seguimiento del envío y cualquier reclamación o comentario relacionado con el envío deberá efectuarse directamente con la empresa del servicio de mensajería.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En caso que la mercancía sea enviada desde diferentes ubicaciones, el Cliente deberá generar las Órdenes de compra necesarias indicando las direcciones de entrega, debiendo pagar los envíos correspondientes. En estos casos, Artesano Online informará previamente al Cliente que se requerirán envíos adicionales.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online no asume responsabilidad por retrasos en la entrega o imposibilidad de realizar la entrega cuando dichos retrasos o imposibilidad de cumplimiento derive de algún caso fortuito, fuerza mayor y, en general, de cualquier causa fuera del control de Artesano Online. En caso de que la empresa de mensajería no logre entregar el artículo en tres visitas al Cliente, el artículo será regresado a Artesano Online. Y el cliente deberá pagar un nuevo servicio de envío y almacenaje.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En caso de las entregas al extranjero, el Cliente pagará los gastos de envío que aparecen en la Orden de Compra. Si el Cliente quiere devolver la mercancía, este deberá pagar el costo del regreso de la mercancía de la Orden de Compra. En caso de que el Cliente requiera un cambio de producto, este tendrá que pagar el costo de envío de la ida y la vuelta de mercancía de acuerdo a la nueva Orden de Compra</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">XIV.- Cancelación de Órdenes de Compras por parte del Cliente.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online podrá ofrecer al Cliente el cambio de la mercancía adquirida por otros productos o bien, en caso de que el Cliente no desee un cambio del mismo podrá optar por la cancelación de sin ninguna penalización.</span></span></span></span></span></span></span></p>

<p style="line-height:1.295; margin-bottom:11px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En Artículos hechos a la medida o marcados como “Piezas de colección”” no hay cambios ni devoluciones</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Roboto,sans-serif"><span style="color:#2f2f30"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"> </span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Roboto,sans-serif"><span style="color:#2f2f30"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">a menos que tengan un defecto de producción.</span></span></span></span></span></span></span></p>

<p style="line-height:1.295; margin-bottom:11px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Por cuestiones de higiene, no se aceptan cambios en ropa de cama y blancos.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En caso de defectos en la mercancía, el Cliente podrá solicitar la devolución de la misma. En caso que dichos defectos sean atribuibles a Artesano Online esta pagará los costos de envío y recuperación de la mercancía.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online responderá por los cambios de las piezas dañadas por el servicio de mensajería siempre y cuando el Cliente documente dicho daño con imágenes legibles donde se muestre el empaque completo, la guía pegada al empaque y el daño en la pieza considerando los siguientes aspectos:</span></span></span></span></span></span></span></p>

<p style="line-height:1.2"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">•</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"><span style="white-space:pre"> </span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Daño visible en la caja. Debe mostrar el exterior de toda la caja o empaque</span></span></span></span></span></span></span></p>

<p style="line-height:1.2"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">•</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"><span style="white-space:pre"> </span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Guía adherida al empaque. Debe mostrar cómo se recibe el paquete&nbsp;</span></span></span></span></span></span></span></p>

<p style="line-height:1.2"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">•</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"><span style="white-space:pre"> </span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Si la caja presenta alguna violación al sello. Debe mostrar estos detalles o signos de violación</span></span></span></span></span></span></span></p>

<p style="line-height:1.2"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">•</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"><span style="white-space:pre"> </span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Daño al producto dentro de la caja. Debe mostrar el empaque interior captando toda la caja&nbsp;</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">•</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"><span style="white-space:pre"> </span></span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Producto dañado. Debe mostrar los imperfectos y fracturas de la pieza</span></span></span></span></span></span></span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En términos de la Ley Federal de Protección al Consumidor, los Clientes tendrán derecho de revocar su consentimiento una vez que reciban la mercancía solicitada a través de la Orden de Compra, dentro de los 5 (cinco) días siguientes a la fecha de entrega de la mercancía. En este caso, el Cliente absorberá los costos de flete correspondientes a su código postal y volumen de la orden. Este derecho no será aplicable para productos perecederos o que puedan caducar dentro del plazo mencionado.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Para el caso de los casos descritos anteriormente “Piezas de Colección” no hay cambios ni devoluciones</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Roboto,sans-serif"><span style="color:#2f2f30"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none"> </span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Roboto,sans-serif"><span style="color:#2f2f30"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">a menos que tengan un defecto de producción</span></span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">XV.- Penas Convencionales</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Si alguna de las partes incumple con las obligaciones del presente contrato fuera de los casos previstos en este instrumento, será acreedor a una pena convencional de conformidad con lo señalado en el artículo 92 TER de la Ley Federal de Protección al Consumidor, más los gastos efectuados efectivamente comprobables.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">En caso de que el Cliente se retrase en la recepción de la mercancía objeto del presente una vez que Artesano Online le notifique que su pedido está listo para ser entregado y/o se confirme la fecha de entrega por parte del Cliente, éste deberá pagar a Artesano Online cargos adicionales por el o los fletes correspondientes; así como por costos de almacenaje generados, los cuales serán informados por Artesano Online al Cliente y deberán de ser cubiertos con anterioridad a la entrega respectiva.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">XVI.- Medidas de Seguridad.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online se reserva el derecho de tomar acciones unilaterales (incluyendo el dar de baja, desactivar o inhabilitar la cuenta de cualquier Cliente o inhabilitar su contraseña en cualquier momento) cuando dichas acciones resulten necesarias para mantener la seguridad del Sitio web y/o de las cuentas de los Clientes; también podrá solicitar información adicional del Cliente a empresas que nos apoyan en procesos de prevención e investigación de fraudes, para efectos de evaluar si debemos o no autorizar o cancelar una transacción.</span></span></span></span></span></span></span></p>

<p style="line-height:1.2; text-align:justify; margin-bottom:10px"><span style="font-size:11px;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="font-family:Arial"><span style="color:#333333"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Artesano Online ha adoptado medidas de seguridad técnicas, físicas y administrativas para proteger su cuenta y el Sitio; sin embargo, Artesano Online no puede proteger la información del Cliente fuera del Sitio. Si el Cliente solicita información a través de correo electrónico, la información que Artesano Online le haga llegar podría estar siendo transmitida o almacenada sin utiliz</span></span></span></span></span></span></span></p></div>